export const footerStyles = {
  body: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: "191px",
    flexDirection: { xs: "unset", md: "column" },
    alignItems: "center",
  },
  container: {
    display: { xs: "none", md: "flex" },
    justifyContent: "space-evenly",
    alignItems: "center",
    height: "359px",
    width: "90%",
    backgroundColor: "#F9FFF7",
    borderRadius: "20px",
  },
  boxFooter: {
    width: "40%",
    height: "80%",
    display: "flex",
    flexDirection: "column",
    // justifyContent: "space-between",
    alignItems: "start",
    gap: "21.7px",
    marginTop: "74.3px",
    paddingLeft: "62px",
  },
  textAlamat: {
    width: "335px",
    height: "60px",
    fontWeight: "400",
    fontsize: "14px",
    lineHeight: "20px",
    textAlign: "start",
  },
  iconFooter: {
    borderRadius: "50%",
    backgroundColor: "white",
    padding: "10px",
    color: "#8BAC3E",
    "&:hover": {
      background: "#8BAC3E",
      color: "white",
    },
  },
  categories: {
    width: "15%",
    height: "80%",
    display: "flex",
    flexDirection: "column",
    marginTop: "79px",
    textAlign: "start",
  },
  itemCategories: {
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  fontTitleFooter: {
    fontWeight: "600",
    fontsize: "18px",
    lineHeight: "24px",
    marginBottom: "33px",
  },
  boxInput: {
    display: "flex",
    width: "250px",
    height: "40px",
    border: "1px black solid",
    borderRadius: "10px",
    overflow: "hidden",
    marginTop: "20px",
  },
  footerTag: {
    fontWeight: " 400",
    fontSize: "12px",
    lineHeight: " 16px",
    letterSpacing: "0.05em",
    textAlign: "center",
    margin: "48px 0 28px 0",
    display: { xs: "none", md: "unset" },
  },
  BoxRight: {
    width: "30%",
    height: "80%",
    display: "flex",
    flexDirection: "column",
    marginTop: "79px",
  },
};
