export const mainBannerStyles = {
  body: {
    position: "relative",
    overflow: "hidden",
    width: "100%",

    "&::before": {
      content: '""',
      backgroundImage: 'url("../../../image/Logo/115 1.svg")',
      position: "absolute",
      backgroundSize: { xs: "contain", md: "cover" },
      top: "0",
      right: "0",
      left: "0",
      bottom: "0",
      opacity: "0.1",
    },
  },
  BoxLeftItem: {
    width: { xs: "100%", md: "50%" },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  boxItem: {
    display: "flex",
    flexDirection: "column",
    width: { xs: "100vh", md: "482px" },
    height: { xs: "100%", md: "unset" },
    gap: "32px",
    textAlign: "start",
    justifyContent: { xs: "space-between", md: "unset" },
    marginLeft: { xs: "30px", md: "unset" },
  },
  goodFood: {
    fontSize: { xs: "40px", md: "64px" },
    fontWeight: "600",
    lineHeight: "64px",
    color: "#8BAC3E",
    marginTop: { xs: "30px", md: "unset" },
  },
  textLeft: {
    fontSize: { xs: "14px", md: "18px" },
    fontWeight: "400",
    lineHeight: { xs: "20px", md: "32px" },
    width: { xs: "90%", md: "unset" },
    marginBottom: { xs: "30px", md: "unset" },
  },
  btnAbout: {
    backgroundColor: "#F2F2F2",
    borderRadius: "20px",
    width: { xs: "80px", md: "98px" },
    height: { xs: "30px", md: "42px" },
    color: "black",
    marginLeft: "20px",
    "&:hover": {
      background: "#8BAC3E",
      color: "white",
    },
    fontSize: { xs: "10px", md: "14px" },
  },
  boxRight: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "50%",
  },
  boxBAckground: {
    backgroundColor: "#C4C4C4",
    width: { xs: "200px", md: "519px" },
    height: { xs: "200px", md: "519px" },
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: { xs: "absolute", md: "relative" },
    left: { xs: "40px", md: "unset" },
  },
  boxReceipt5Str: {
    display: "flex",
    position: "absolute",
    bottom: { xs: "0px", md: "20px" },
    left: { xs: "unset", md: "-65px" },
    right: { xs: "-100px", md: "unset" },
    gap: "20px",
    width: { xs: "200px", md: "292px" },
    height: { xs: "60px", md: "93px" },
    background: "rgba(255, 255, 255, 0.74)",
    boxShadow: "0px 11px 39px rgba(0, 0, 0, 0.07)",
    backdropFilter: "blur(5.5px)",
    borderRadius: { xs: "10px", md: "17px" },
    alignItems: "center",
  },
  tomato: {
    fontSize: { xs: "10px", md: "12px" },
    fontWeight: "400",
    lineHeight: { xs: "8px", md: "14px" },
    color: "rgba(196, 196, 196, 1)",
  },
  saladTomato: {
    fontSize: { xs: "10px", md: "14px" },
    fontWeight: "600",
    lineHeight: { xs: "12px", md: "22px" },
  },
  imageFood: {
    width: { xs: "40px", md: "53px" },
    paddingLeft: "20px",
  },
};
